# Generated by Django 4.0.3 on 2022-06-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsrss',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_rss_in_group', to='rss_catalog.newsrssgroups'),
        ),
        migrations.AlterField(
            model_name='newsrss',
            name='rss_source',
            field=models.URLField(blank=True),
        ),
    ]
