# Generated by Django 4.0.3 on 2022-06-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status_model', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_in_status', to='status_model.statustypes'),
        ),
        migrations.DeleteModel(
            name='PubStatus',
        ),
    ]
