# Generated by Django 4.0.3 on 2022-06-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_alter_postingallery_location'),
        ('news', '0002_alter_news_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLocations',
        ),
    ]
