# Generated by Django 4.0.3 on 2022-06-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_status_delete_pubstatus'),
        ('news', '0003_delete_newslocations'),
    ]

    operations = [
    ]
