# Generated by Django 4.0.3 on 2022-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_20220629_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_short',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
