# Generated by Django 4.0.3 on 2022-05-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_time_end_remove_events_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_type_in_events', to='events.eventtypes'),
        ),
    ]
