# Generated by Django 4.0.3 on 2022-06-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status_model', '0001_initial'),
        ('events', '0004_alter_events_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_in_status', to='status_model.statustypes'),
        ),
        migrations.DeleteModel(
            name='EventStatusTypes',
        ),
    ]
