# Generated by Django 4.0.3 on 2022-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_event_status_delete_eventstatustypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventformats',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventtypes',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
