# Generated by Django 4.0.3 on 2022-06-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
        ('tags', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('alt_text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='photo_gallery/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_gallery_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_gallery_location', to='news.newslocations')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_gallery_in_subjects', to='subjects.subjects')),
                ('tags', models.ManyToManyField(related_name='gallery_tags', to='tags.tags')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
