# Generated by Django 4.0.3 on 2022-06-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingallery',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_gallery_in_subjects', to='subjects.subjects'),
        ),
    ]
