# Generated by Django 4.0.3 on 2022-06-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('photo_gallery', '0002_alter_postingallery_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingallery',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_gallery_location', to='location.location'),
        ),
    ]
