# Generated by Django 4.0.3 on 2022-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0005_delete_galleryformats_delete_gallerytypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingallery',
            name='author',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
