# Generated by Django 4.0.3 on 2022-07-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status_model', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SciPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.URLField()),
                ('short_description', models.TextField()),
                ('authors', models.ManyToManyField(related_name='scipop_authors', to='sci_pop.authors')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sci_pop_created', to=settings.AUTH_USER_MODEL)),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_in_format', to='sci_pop.popformat')),
                ('sci_pop_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sci_pop_in_status', to='status_model.statustypes')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scipop_in_subjects', to='subjects.subjects')),
                ('tags', models.ManyToManyField(related_name='scipop_tags', to='tags.tags')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
