# Generated by Django 4.0.3 on 2022-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_pop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scipop',
            name='ddate_video',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
