# Generated by Django 4.0.3 on 2022-07-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_pop', '0002_scipop_ddate_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scipop',
            old_name='ddate_video',
            new_name='date_video',
        ),
    ]
