# Generated by Django 4.0.3 on 2022-07-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_pop', '0004_scipopmoderatorcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='title',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='scipop',
            old_name='short_description',
            new_name='description',
        ),
    ]
