# Generated by Django 4.0.3 on 2022-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_pop', '0005_rename_title_authors_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scipop',
            name='material_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
