# Generated by Django 4.0.3 on 2022-07-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_pop', '0006_scipop_material_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scipop',
            old_name='date_published',
            new_name='published_at',
        ),
    ]
