# Generated by Django 4.0.3 on 2022-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_catalog', '0002_layersviewset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layersviewset',
            name='layers',
        ),
        migrations.AddField(
            model_name='layersviewset',
            name='layers',
            field=models.ManyToManyField(related_name='viewset_in_layers', to='metadata_catalog.layers'),
        ),
    ]
