# Generated by Django 4.0.3 on 2022-06-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_catalog', '0003_remove_layersviewset_layers_layersviewset_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layers',
            name='layer_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers_in_groups', to='metadata_catalog.layergroups'),
        ),
        migrations.AlterField(
            model_name='layers',
            name='layer_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers_in_types', to='metadata_catalog.layertypes'),
        ),
        migrations.AlterField(
            model_name='layers',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers_in_services', to='metadata_catalog.services'),
        ),
    ]
