# Generated by Django 4.0.3 on 2022-06-24 09:31

import apps.metadata_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_catalog', '0004_alter_layers_layer_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersviewset',
            name='layers_tree',
            field=models.JSONField(default=apps.metadata_catalog.models.layers_tree_default),
        ),
    ]
