# Generated by Django 4.0.3 on 2022-07-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('subjects', '0001_initial'),
        ('status_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SciPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('source_date', models.CharField(max_length=255)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='pdf_file/', verbose_name='file')),
                ('summary', models.CharField(max_length=255)),
                ('release', models.CharField(blank=True, max_length=255, null=True)),
                ('url_reference', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('authors', models.ManyToManyField(related_name='scipub_authors', to='sci_pub.authors')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sci_pub_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scipub_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SciPubModeratorComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scipub_comments_created', to=settings.AUTH_USER_MODEL)),
                ('scipub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scipub_comments', to='sci_pub.scipub')),
            ],
        ),
        migrations.AddField(
            model_name='scipub',
            name='scipub_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub_in_source', to='sci_pub.source'),
        ),
        migrations.AddField(
            model_name='scipub',
            name='scipub_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub_in_status', to='status_model.statustypes'),
        ),
        migrations.AddField(
            model_name='scipub',
            name='scipub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub_in_type', to='sci_pub.pubtype'),
        ),
        migrations.AddField(
            model_name='scipub',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scipub_in_subjects', to='subjects.subjects'),
        ),
        migrations.AddField(
            model_name='scipub',
            name='tags',
            field=models.ManyToManyField(related_name='scipub_tags', to='tags.tags'),
        ),
    ]
